### ISSUE TITLE
Debian release for 0.4.3

### ISSUE THREAD

**Issue by christianrauch** [colcon/colcon-meson#12]
@nuclearsandwich @cottsay I released 0.4.3 to PyPI to adapt to the (private) API of newer meson versions (>=1.3). Can one of you release a new Debian package?

Since we are at it, how do you release a RPM package for colon extensions? Similar to `python3-colcon-cmake`, I would like to do `dnf install python3-colcon-colcon` on RHEL and derivatives.

**Comment by cottsay** [comment]
Alright, I did the debian package release: ros-infrastructure/reprepro-updater#205

For the RPMs, I actually just "upstream" the packages into Fedora/EPEL and keep them up-to-date. I've re-opened the package review request for colcon-meson: https://bugzilla.redhat.com/show_bug.cgi?id=2117349

**Comment by christianrauch** [comment]
Thanks! Is releasing an update to the Debian package as easy as sending a PR to https://github.com/ros-infrastructure/reprepro-updater and this runs somewhere in the background and generates a new deb file? Or does one of you always have to build this manually on a server and the repo is just indexing the externally built package?

**Comment by cottsay** [comment]
Unfortunately it's not so simple. The Debian first need to be built and imported into the [packagecloud repository](https://packagecloud.io/dirk-thomas/colcon). Instructions here: https://colcon.readthedocs.io/en/released/developer/release.html#publishing-a-release

Importing from the colcon repo into the ROS repo starts with that PR, but involves manual steps after merging. Instructions here: https://github.com/ros-infrastructure/reprepro-updater/pull/135/files?short_path=ab5ad5d#diff-ab5ad5d12efee924090574b1150a5cde9333721bf87b6beab27731df27d46659

**Comment by christianrauch** [comment]
I see. I would also need an account and access to packagecloud.io. Any chance this gets automated via the CI at some point in the future? :-) Do you think I should do this on my own or are you happy to do this from time to time? I am asking as I actually would like to release 0.4.4.

**Comment by cottsay** [comment]
> I would also need an account and access to packagecloud.io.

Correct. Unfortunately, I'm not capable of granting that ability right now.

> Any chance this gets automated via the CI at some point in the future?

Possibly, but probably no time soon.

> Do you think I should do this on my own or are you happy to do this from time to time?

I'm happy to push releases for now. This was a good workflow - just open an issue and tag/assign me.

**Comment by christianrauch** [comment]
@cottsay Can you make a new Debian release for the latest [`0.4.5`](https://github.com/colcon/colcon-meson/releases/tag/0.4.5) tag?

**Comment by cottsay** [comment]
> Can you make a new Debian release for the latest [`0.4.5`](https://github.com/colcon/colcon-meson/releases/tag/0.4.5) tag?

Sorry for the delay: ros-infrastructure/reprepro-updater#208

**Comment by christianrauch** [comment]
Thanks.

**Comment by cottsay** [comment]
Better late than never, this package is now headed for Fedora and EPEL 9: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-a57d2f126c

It should arrive in the stable repositories in about a week.
